/* eslint-disable  */
import Vue from 'vue';
import DividerV from './Divider/DividerV.vue';
import HoverList from './list/HoverList.vue';
import Empty from './Empty/Empty.vue';
import Tag from './Tag/Tag.vue';
import Search from './Search/Search.vue';
import Action from './action/Action.vue';
import Upload from './Upload/Upload.vue';
import ModalUser from './Modal/User';
import ModalRider from './Modal/Rider';
import ModalTaker from './Modal/Taker';
import ColorPicker from './Color/ColorPicker';
import UserLink from './UserLink/UserLink';
import AdminLink from './UserLink/AdminLink';
import AgentLink from './UserLink/AgentLink';
import RiderLink from './UserLink/RiderLink';
import TakerLink from './UserLink/TakerLink';
import DatePicker from './Date/DatePicker';
import FEditor from './Editor/Editor';
import Picture from './Picture/Picture';
import UploadImage from './Upload/UploadImage';
import UploadRichtext from './Upload/UploadRichtext';

Vue.component('CDividerV', DividerV);
Vue.component('CHoverList', HoverList);
Vue.component('CEmpty', Empty);
Vue.component('CTag', Tag);
Vue.component('Search', Search);
Vue.component('Action', Action);
Vue.component('Upload', Upload);
Vue.component('ModalUser', ModalUser);
Vue.component('ModalTaker', ModalTaker);
Vue.component('ModalRider', ModalRider);
Vue.component('ColorPicker', ColorPicker);
Vue.component('UserLink', UserLink);
Vue.component('AdminLink', AdminLink);
Vue.component('AgentLink', AgentLink);
Vue.component('RiderLink', RiderLink);
Vue.component('TakerLink', TakerLink);
Vue.component('DatePicker', DatePicker);
Vue.component('FEditor', FEditor);
Vue.component('CPicture', Picture);
Vue.component('UploadImage', UploadImage);
Vue.component('UploadRichtext', UploadRichtext);

export default null;
